### ISSUE TITLE
可以做下网易新闻登录的吗

### ISSUE THREAD

**Issue by mango941231** [IMWoolei/fuck-login#1]

**Comment by imleowoo** [comment]
我先试一下吧，之前试过网易家的163邮箱那个样子有点难搞

**Comment by mango941231** [comment]
嗯谢谢您 获取完cookie后您做过接下来的评论点赞吗 我遇到一些问题

**Comment by imleowoo** [comment]
网易新闻的点赞我之前做过，是不需要账号就能点赞的，做法是抓网易新闻手机APP的包来进行点赞操作，只需要切换代理IP就行了，你可以试试。如果有问题的话我之后把我的程序放上来

**Comment by imleowoo** [comment]
目前发现的问题就是当频繁点赞过多之后，网易那边可能会视为异常评论而吞贴

**Comment by mango941231** [comment]
可以加下联系方式吗

**Comment by mango941231** [comment]
我的q 1119197389

**Comment by imleowoo** [comment]
已加好友
